%% h2
Fragment.dataMerge({'h2\h2Dat.mat', ...
    'data\h2_field_MP2\h2_field_MP2.mat'}, {1:10, 21:30}, ...
    'datasets\h2Dat.mat', 'nHLbasis', 1);

%% ch4
Fragment.dataMerge({'ch4\ch4Dat.mat', ...
    'data\ch4_field_MP2\ch4_field_MP2.mat'}, {1:10, 21:30}, ...
    'datasets\ch4Dat.mat', 'nHLbasis', 1);

%% ethane
Fragment.dataMerge({'data\ethaneDat.mat', ...
    'data\ethane_field_MP2\ethane_field_MP2.mat'}, {1:10, 21:30}, ...
    'datasets\ethaneDat.mat', 'nHLbasis', 1);

%% ethylene
Fragment.dataMerge({'ethylene1mp2\ethyleneDat.mat', ...
    'data\ethylene_field_MP2\ethylene_field_MP2.mat'}, {1:10, 21:30}, ...
    'datasets\ethyleneDat.mat', 'nHLbasis', 1);
